'use strict';
var https = require('https');

var BILLING_CODES = [
  "H101 (ED Assessment): Minor assessment – Day (8am–5pm) -- Exact fee $23.00",
  "H102 (ED Assessment): Comprehensive assessment – Day (8am–5pm) -- Exact fee $57.00",
  "H103 (ED Assessment): Multiple assessment – Day (8am–5pm) -- Exact fee $47.00",
  "H104 (ED Assessment): Reassessment – Day (8am–5pm) -- >2h, change mgmt, not d/c or referral; max 3/pt/day -- Exact fee $23.00",
  "H131 (ED Assessment): Minor assessment – Eve Mon–Thu (5pm–midnight) -- Exact fee $30.00",
  "H132 (ED Assessment): Comprehensive assessment – Eve Mon–Thu (5pm–midnight) -- Exact fee $75.00",
  "H133 (ED Assessment): Multiple assessment – Eve Mon–Thu (5pm–midnight) -- Exact fee $62.00",
  "H134 (ED Assessment): Reassessment – Eve Mon–Thu (5pm–midnight) -- >2h, change mgmt; max 3/pt/day -- Exact fee $30.00",
  "H121 (ED Assessment): Minor assessment – Night (midnight–8am) -- Exact fee $40.00",
  "H122 (ED Assessment): Comprehensive assessment – Night (midnight–8am) -- Exact fee $100.00",
  "H123 (ED Assessment): Multiple assessment – Night (midnight–8am) -- Exact fee $81.00",
  "H124 (ED Assessment): Reassessment – Night (midnight–8am) -- >2h, change mgmt; max 3/pt/day -- Exact fee $40.00",
  "H151 (ED Assessment): Minor assessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight -- Exact fee $34.00",
  "H152 (ED Assessment): Comprehensive assessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight -- Exact fee $86.00",
  "H153 (ED Assessment): Multiple assessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight -- Exact fee $70.00",
  "H154 (ED Assessment): Reassessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight; max 3/pt/day -- Exact fee $34.00",
  "H112 (Premiums): Night premium (midnight–8am) -- Per patient visit -- Exact fee $51.00",
  "H113 (Premiums): Wkd/Hol + Fri eve premium -- Per patient visit; incl Fri eve 5pm–midnight -- Exact fee $32.00",
  "H114 (Premiums): Weekday eve premium (Mon–Thu) -- Per patient visit; NEW April 2026 -- Exact fee $24.00",
  "H055 (Consultations): Consultation to ED – FRCPC -- Must record referring MD billing # or contact info -- Exact fee $126.00",
  "H065 (Consultations): Consultation to ED – CFPC -- Must record referring MD billing # or contact info -- Exact fee $96.00",
  "K734 (Consultations): Phone consult – referring physician -- ≥10 min; cannot lead to follow-up -- Exact fee $31.00",
  "K735 (Consultations): Phone consult – consultant physician -- ≥10 min; cannot lead to follow-up -- Exact fee $40.00",
  "K736 (Consultations): CritiCall telephone consultation – referring physician -- Exact fee $32.45 -- Exact fee $32.00",
  "H960 (On-Call): On-call travel – Weekday Day -- Max 2/day -- Exact fee $37.00",
  "H962 (On-Call): On-call travel – Weekday Eve -- Max 2 -- Exact fee $37.00",
  "H963 (On-Call): On-call travel – Wkd/Hol -- Max 4 -- Exact fee $37.00",
  "H964 (On-Call): On-call travel – Night -- Unlimited -- Exact fee $37.00",
  "H980 (On-Call): On-call 1st patient – Weekday Day -- Max 5 -- Exact fee $20.00",
  "H984 (On-Call): On-call 1st patient – Weekday Eve -- Max 5 -- Exact fee $60.00",
  "H968 (On-Call): On-call 1st patient – Wkd/Hol -- Max 10 -- Exact fee $75.00",
  "H986 (On-Call): On-call 1st patient – Night -- Unlimited -- Exact fee $100.00",
  "H981 (On-Call): On-call addl patient – Weekday Day -- Max 5 -- Exact fee $20.00",
  "H985 (On-Call): On-call addl patient – Weekday Eve -- Max 5 -- Exact fee $60.00",
  "H989 (On-Call): On-call addl patient – Wkd/Hol -- Max 10 -- Exact fee $75.00",
  "H987 (On-Call): On-call addl patient – Night -- Unlimited -- Exact fee $100.00",
  "K005 (Counselling / Forms): Mental health counselling -- Min 20 min; document mental health dx + times -- Exact fee $63.00",
  "K061 (Counselling / Forms): Blood sample at request of police officer -- Taking blood in hospital for forensic/legal purposes (e.g. impaired driving); exact fee ~$34.80 -- Exact fee $35.00",
  "K028 (Counselling / Forms): Needlestick or STI counselling/treatment -- Per 30 min; document times. Fee updated April 1 2026 -- Exact fee $80.00",
  "K034 (Counselling / Forms): Telephone report of reportable disease to MOH -- Max 1 per physician per patient per disease per 12 months; must be personally rendered by physician -- Exact fee $36.00",
  "K015 (Counselling / Forms): Counsel family re: death/catastrophe -- Min 20 min; document times -- Exact fee $63.00",
  "K623 (Counselling / Forms): Form 1 – psychiatric assessment -- Exact fee $105.00",
  "K070 (Counselling / Forms): Homecare application -- Exact fee $32.00",
  "K071 (Counselling / Forms): Acute Home Care Supervision -- Exact fee $21.40; max 1 per physician per patient per 2 weeks; first 12 weeks following admission to home care program -- Exact fee $21.00",
  "K035 (Counselling / Forms): Medical conditions report -- Mandatory report to MOT; exact fee $36.25 (MOH Jan 2025) -- Exact fee $36.00",
  "A771 (Counselling / Forms): Death certificate -- Exact fee $34.00",
  "A777 (Counselling / Forms): Pronouncement + death certificate -- Exact fee $34.00",
  "H105 (Counselling / Forms): Interim admission orders -- Exact fee $29.00",
  "A320 (Counselling / Forms): MAID consultation -- NEW April 2026; exact fee $174.25 -- Exact fee $174.00",
  "K101 (Transport): Ground ambulance transfer with patient -- Per 15 min; physician attendance during ground ambulance transfer; fee updated April 1 2026 -- Exact fee $60.00",
  "K111 (Transport): Air ambulance transfer with patient -- Per 15 min; physician attendance during air ambulance transfer; fee updated April 1 2026 -- Exact fee $60.00",
  "K112 (Transport): Return trip without patient to place of origin -- Per 30 min; air and ground ambulance; companion to K101/K111 -- Exact fee $25.00",
  "G521 (Critical Care - Imminent): Imminent life-threatening: 1st 15 min (1st MD) -- Arrest/Trauma; document times; cannot see other pts simultaneously; exact fee $111.80 (MOH Jan 2025). <strong>E420 +50% trauma premium (ISS > 15)</strong> -- Exact fee $112.00",
  "G523 (Critical Care - Imminent): Imminent life-threatening: 2nd 15 min (1st MD) -- Arrest/Trauma; exact fee $57.65 (MOH Jan 2025) -- Exact fee $58.00",
  "G522 (Critical Care - Imminent): Imminent life-threatening: each addl 15 min (max 6) -- Arrest/Trauma; bill for 2nd/3rd MD too; exact fee $38.00 (MOH Jan 2025) -- Exact fee $38.00",
  "E420 (Critical Care - Imminent): Trauma ISS > 15 premium -- Add to critical care codes",
  "G395 (Critical Care - Potential): Potential life-threatening: 1st 15 min -- Other resuscitation; document times; exact fee $57.45 (MOH Jan 2025) -- Exact fee $57.00",
  "G391 (Critical Care - Potential): Potential life-threatening: each addl 15 min (max 7) -- Bill for 2nd/3rd MD too; exact fee $30.60 (MOH Jan 2025) -- Exact fee $31.00",
  "Z437 (Critical Care - Other Procedures): Cardioversion (max 3/day) -- Allowed with G395 but NOT G521 -- Exact fee $92.00",
  "Z443 (Critical Care - Other Procedures): Insertion of transvenous pacemaker -- Exact fee $154.10",
  "Z431 (Critical Care - Other Procedures): Repositioning of pacemaker wire -- Exact fee $64.25",
  "G269 (Critical Care - Other Procedures): Central line -- Exact fee $31.00",
  "G211 (Critical Care - Other Procedures): Intubation -- Allowed with G395 but NOT G521; exact fee $38.35 (MOH Jan 2025) -- Exact fee $38.00",
  "Z325 (Critical Care - Other Procedures): Emergency tracheotomy -- Only billable for life-threatening emergencies where patient is not intubated -- Exact fee $474.65",
  "E013C (Critical Care - Other Procedures): Anaesthetic management – acute upper airway obstruction (above carina, excl. choanal atresia) -- 10 basic units · Do not bill other C-suffix procedure codes for the same procedure -- Exact fee $159.60",
  "E639 (Critical Care - Other Procedures): Emergency tracheotomy – anterior cricoid split (add-on) -- Add to Z325 -- Exact fee $78.50",
  "Z341 (Critical Care - Other Procedures): Chest tube (tube thoracostomy for closed drainage) -- Exact fee $76.80",
  "Z363 (Critical Care - Other Procedures): Chest tube removal (thoracostomy tube) -- Incl wound closure; fee as of April 1 2026 -- Exact fee $22.60",
  "Z611 (Critical Care - Other Procedures): Catheter -- Exact fee $8.55 (MOH Jan 2025) -- Exact fee $9.00",
  "H100 (Critical Care - Other Procedures): Ultrasound -- Exact fee $20.00",
  "E009 (Anaesthesia Modifiers): Patient < 1 year old -- Add C4 units; 1 unit = $15.96 (April 2026)",
  "E019 (Anaesthesia Modifiers): Patient 1–8 years old -- Add C2 units",
  "E007 (Anaesthesia Modifiers): Patient 70–79 years old -- Add C1 unit",
  "E018 (Anaesthesia Modifiers): Patient > 80 years old -- Add C3 units",
  "E011 (Anaesthesia Modifiers): Prone position -- Add C4 units",
  "E024 (Anaesthesia Modifiers): Sitting position -- Add C4 units",
  "E022 (Anaesthesia Modifiers): ASA III -- Add C2 units",
  "E017 (Anaesthesia Modifiers): ASA IV -- Add C10 units",
  "E016 (Anaesthesia Modifiers): ASA V -- Add C20 units",
  "E020 (Anaesthesia Modifiers): ASA E (emergency) -- Add C4 units",
  "E010 (Anaesthesia Modifiers): BMI > 40 -- Add C2 units",
  "E400 (Anaesthesia Modifiers): Eve/Wkd/Hol time qualifier -- 3rd line; C = sum of steps 2+3 units",
  "E401 (Anaesthesia Modifiers): Overnight time qualifier -- 3rd line; C = sum of steps 2+3 units",
  "E413 (Anaesthesia Modifiers): Procedure premium – Overnight -- +40% on anaesthesia",
  "E412 (Anaesthesia Modifiers): Procedure premium – Eve/Wkd/Hol -- +20% on anaesthesia",
  "Z154 (Sutures): Face suture 0–5 cm -- Adhesive strips/glue = 50% of fee -- Exact fee $39.00",
  "Z177 (Sutures): Face suture 5.1–10 cm -- 50% of fee if closed with glue or steri-strips -- Exact fee $78.00",
  "Z190 (Sutures): Face suture 10.1–15 cm -- Exact fee $111.00",
  "Z192 (Sutures): Face suture > 15 cm -- Exact fee $170.00",
  "Z176 (Sutures): Body suture 0–5 cm -- 50% of fee if closed with glue or steri-strips -- Exact fee $22.00",
  "Z175 (Sutures): Body suture 5.1–10 cm -- 50% of fee if closed with glue or steri-strips -- Exact fee $39.00",
  "Z179 (Sutures): Body suture 10.1–15 cm -- 50% of fee if closed with glue or steri-strips -- Exact fee $55.00",
  "Z191 (Sutures): Body suture > 15 cm -- Exact fee $85.00",
  "R024 (Complex Lacerations): Acute earlobe repair -- > 20 min; document times -- Exact fee $101.00",
  "Z189 (Complex Lacerations): Complex laceration zone 1 -- > 20 min; document times -- Exact fee $92.00",
  "Z187 (Complex Lacerations): Complex face laceration -- > 20 min; document times -- Exact fee $92.00",
  "R606 (Complex Lacerations): Phalanx amputation repair -- Exact fee $161.00",
  "Z188 (Complex Lacerations): Complex non-face laceration -- > 20 min; document times -- Exact fee $92.00",
  "P036 (Complex Lacerations): Vaginal laceration repair -- Exact fee $54.00",
  "R525 (Complex Lacerations): Muscle & skin repair -- Exact fee $89.00",
  "R578 (Complex Lacerations): Extensor tendon repair -- Exact fee $164.00",
  "J149C (Routine Procedures): U/S guided procedure -- Exact fee $47.00",
  "G269 (Routine Procedures): Central line -- Exact fee $31.00",
  "G224 (Routine Procedures): Nerve block – local, >4h duration (not a named anatomic block) -- Not billable with lacerations. Use for pudendal, femoral, intercostal, sciatic, ilioinguinal, ulnar, median, radial, or brachial blocks. If a more specific OHIP code exists for the block (e.g. G060, G218, G220), use that instead. -- Exact fee $16.00",
  "G268 (Routine Procedures): Arterial line -- Exact fee $31.00",
  "G060 (Routine Procedures): Major nerve block (provides analgesia > 4h) -- Exact fee $55.00",
  "G061 (Routine Procedures): Minor nerve block (provides analgesia > 4h) -- Exact fee $30.00",
  "G260 (Routine Procedures): Major plexus block – 3-in-1 (provides analgesia > 4h) -- Exact fee $80.00",
  "G231 (Routine Procedures): Dental block -- Exact fee $34.00",
  "G370 (Routine Procedures): Knee aspiration -- Exact fee $20.00",
  "G328 (Routine Procedures): Joint aspiration (not knee) -- Exact fee $40.00",
  "E446 (Routine Procedures): U/S guided aspiration (addl) -- Add-on code -- Exact fee $30.00",
  "Z080 (Routine Procedures): Wound/ulcer debridement -- Exact fee $20.00",
  "Z331 (Routine Procedures): Diagnostic thoracentesis -- Exact fee $32.00",
  "Z332 (Routine Procedures): Therapeutic thoracentesis -- Exact fee $59.00",
  "Z590 (Routine Procedures): Diagnostic paracentesis -- Exact fee $31.00",
  "Z591 (Routine Procedures): Therapeutic paracentesis -- Exact fee $58.00",
  "Z763 (Routine Procedures): Paracentesis with lavage for diagnosis -- Exact fee $38.70",
  "G356 (Routine Procedures): NG tube insertion -- Exact fee $34.00",
  "Z520 (Routine Procedures): G tube change -- Exact fee $11.00",
  "Z538 (Routine Procedures): Hernia reduction -- Exact fee $25.00",
  "Z543 (Routine Procedures): Anoscopy / Proctoscopy -- Exact fee $9.00",
  "Z110 (Routine Procedures): Subungual hematoma drainage -- Exact fee $17.00",
  "Z608 (Routine Procedures): Manual Foley declogging -- Exact fee $59.00",
  "Z128 (Routine Procedures): Nail removal -- Exact fee $33.00",
  "A920 (Routine Procedures): Misoprostol (including assessment) -- Exact fee $161.00",
  "Z130 (Routine Procedures): Nail removal + cautery -- Exact fee $63.00",
  "S756 (Routine Procedures): Removal of POC from OS -- Exact fee $112.00",
  "G313 (Routine Procedures): EKG -- Must be discharged patient -- Exact fee $4.00",
  "Z804 (Routine Procedures): Lumbar puncture -- Exact fee $150.00",
  "Z399 (Routine Procedures): Endoscopy -- Exact fee $93.00",
  "L810 (Routine Procedures): Description of CSF -- Exact fee $25.00 (MOH Jan 2025) -- Exact fee $25.00",
  "G435 (Routine Procedures): Tonometry -- Exact fee $5.10 (MOH Jan 2025) -- Exact fee $5.00",
  "Z432 (Routine Procedures): Exam under anaesthesia -- Exact fee $54.00",
  "G552 (Routine Procedures): IUD removal (without sedation) -- Removal of intrauterine contraceptive device without sedation -- Exact fee $20.00",
  "Z735 (Routine Procedures): IUD removal / exam ± insertion under GA -- Exam and/or dilatation incl insertion and/or removal of IUD under general anaesthetic as sole procedure -- Exact fee $56.70",
  "Z756 (Routine Procedures): Rectal disimpaction / fecal disimpaction -- Was $36.80 → $46.00 April 2026 -- Exact fee $46.00",
  "H264 (Routine Procedures): ED pelvic exam with speculum -- NEW April 2026 -- Exact fee $12.00",
  "Z101 (Incision & Drainage): Abscess I&D – one abscess (LA) -- Exact fee $28.00",
  "Z226 (Incision & Drainage): Elbow bursa I&D -- Exact fee $97.00",
  "Z102 (Incision & Drainage): Abscess I&D – one abscess (GA) -- Exact fee $49.00",
  "Z506 (Incision & Drainage): Oral abscess I&D -- Exact fee $51.00",
  "Z173 (Incision & Drainage): Abscess I&D – two abscesses (LA) -- Exact fee $33.00",
  "Z714 (Incision & Drainage): Bartholin's cyst I&D (LA) -- Exact fee $17.00",
  "Z174 (Incision & Drainage): Abscess I&D – 3+ abscesses (LA) -- Exact fee $45.00",
  "Z715 (Incision & Drainage): Bartholin's cyst I&D (GA) -- Exact fee $51.00",
  "Z104 (Incision & Drainage): Perianal abscess I&D (LA) -- Was $20.10 → $33.25 (+65%) April 2026 -- Exact fee $33.00",
  "Z140 (Incision & Drainage): Breast abscess I&D (LA) -- Exact fee $33.00",
  "Z105 (Incision & Drainage): Perianal abscess I&D (GA) -- Exact fee $72.00",
  "Z740 (Incision & Drainage): Breast abscess I&D (GA) -- Exact fee $75.00",
  "Z106 (Incision & Drainage): Pilonidal abscess I&D (LA) -- Exact fee $49.00",
  "Z227 (Incision & Drainage): IM abscess/hematoma I&D -- Exact fee $101.00",
  "Z107 (Incision & Drainage): Pilonidal abscess I&D (GA) -- Exact fee $118.00",
  "Z510 (Incision & Drainage): Peritonsillar abscess (PTA) drainage -- Exact fee $91.00",
  "Z545 (Incision & Drainage): Hemorrhoid I&D -- Exact fee $25.00",
  "E318 (Incision & Drainage): Pinna hematoma drainage -- Exact fee $92.00",
  "Z114 (Foreign Bodies): Foreign body removal – skin (LA) -- Exact fee $25.00",
  "Z915 (Foreign Bodies): Foreign body removal – ear (LA) -- Exact fee $11.00",
  "Z115 (Foreign Bodies): Foreign body removal – skin (GA) -- Exact fee $89.00",
  "Z866 (Foreign Bodies): Foreign body removal – ear (GA) -- Exact fee $51.00",
  "R517 (Foreign Bodies): Foreign body removal – muscle -- Exact fee $108.00",
  "Z311 (Foreign Bodies): Foreign body removal – nose (LA) -- Exact fee $11.00",
  "Z541 (Foreign Bodies): Foreign body removal – rectum (GA) -- Exact fee $58.00",
  "Z312 (Foreign Bodies): Foreign body removal – nose (GA) -- Exact fee $51.00",
  "Z847 (Foreign Bodies): Foreign body removal – eye (1 FB) -- Also used for chalazion excision -- Exact fee $33.00",
  "Z848 (Foreign Bodies): Foreign body removal – eye (2 FBs) -- Exact fee $45.00 (MOH Jan 2025) -- Exact fee $45.00",
  "Z852 (Foreign Bodies): Foreign body removal – eye, embedded (GA) -- Exact fee $74.20 -- Exact fee $74.00",
  "Z432A (Foreign Bodies): Foreign body removal – vagina (GA) -- Exact fee $54.00",
  "S547 (Foreign Bodies): Foreign body removal – urethra -- Exact fee $171.00",
  "E023C (Foreign Bodies): Foreign body removal – vagina with sedation -- 6 anaesthesia units",
  "G420 (ENT): Ear syringe/irrigation -- Insured only if: (a) impacted wax causing hearing loss unresponsive to topical cerumenolytics; or (b) immediate removal needed to visualize TM or ear canal for diagnostic/therapeutic purposes -- Exact fee $11.00",
  "G403 (ENT): Epley manoeuvre -- Exact fee $21.00",
  "Z315 (ENT): Anterior nasal pack -- Exact fee $15.00",
  "Z321 (ENT): Direct laryngoscopy -- Exact fee $61.00",
  "Z316 (ENT): Posterior nasal pack -- Unilateral or bilateral -- Exact fee $36.00",
  "Z322 (ENT): Direct laryngoscopy with FB removal -- Exact fee $106.00",
  "Z314 (ENT): Nasal cautery -- Exact fee $12.00",
  "Z301 (ENT): Nasal abscess or haematoma I&D -- Exact fee $55.60 -- Exact fee $56.00",
  "Z324 (ENT): Indirect laryngoscopy with FB removal -- Exact fee $45.00",
  "F136 (ENT): Nasal fracture reduction -- Exact fee $102.00",
  "D062 (ENT): TMJ reduction -- Exact fee $52.00",
  "F004 (Fractures - Upper Extremity): Phalanx finger fracture – closed, no reduction -- Exact fee $49.20 (MOH Jan 2025); add E558 for each additional finger -- Exact fee $49.00",
  "F005 (Fractures - Upper Extremity): Phalanx finger fracture – closed, with reduction -- Ortho f/u = 75%; Exact fee $99.25 (MOH Jan 2025); add E558 for each additional finger -- Exact fee $99.00",
  "E558 (Fractures - Upper Extremity): Phalanx finger – each addl fracture with reduction -- Exact fee $22.25 (MOH Jan 2025) -- Exact fee $22.00",
  "F007 (Fractures - Upper Extremity): Phalanx finger fracture – open, with reduction -- Exact fee $298.45 (MOH Jan 2025) -- Exact fee $298.00",
  "F008 (Fractures - Upper Extremity): Metacarpal fracture – no reduction -- Exact fee $49.20 (MOH Jan 2025) -- Exact fee $49.00",
  "F009 (Fractures - Upper Extremity): Metacarpal fracture – with reduction -- Exact fee $99.25 (MOH Jan 2025) -- Exact fee $99.00",
  "F012 (Fractures - Upper Extremity): Bennett's fracture – no reduction -- Exact fee $49.20 (MOH Jan 2025) -- Exact fee $49.00",
  "F013 (Fractures - Upper Extremity): Bennett's fracture – with reduction -- Exact fee $119.80 (MOH Jan 2025) -- Exact fee $120.00",
  "F018 (Fractures - Upper Extremity): Scaphoid fracture – no reduction -- Exact fee $49.20 (MOH Jan 2025) -- Exact fee $49.00",
  "F102 (Fractures - Upper Extremity): Other carpal fracture – no reduction -- Exact fee $49.20 (MOH Jan 2025) -- Exact fee $49.00",
  "F016 (Fractures - Upper Extremity): Other carpal fracture – with reduction -- Exact fee $115.10 (MOH Jan 2025) -- Exact fee $115.00",
  "F027 (Fractures - Upper Extremity): Colles/Smith fracture – no reduction -- Exact fee $67.75 (MOH Jan 2025) -- Exact fee $68.00",
  "F028 (Fractures - Upper Extremity): Colles/Smith fracture – with reduction -- Exact fee $109.45 (MOH Jan 2025) -- Exact fee $109.00",
  "F046 (Fractures - Upper Extremity): Colles/Smith fracture – with reduction + sedation -- Exact fee $149.35 (MOH Jan 2025) -- Exact fee $149.00",
  "F024 (Fractures - Upper Extremity): Radius and ulna shaft fracture – no reduction, rigid immobilization -- Exact fee $67.75",
  "F014 (Fractures - Upper Extremity): Monteggia fracture – no reduction, rigid immobilization -- Open reduction of ulnar # + closed reduction of radial head dislocation may be claimed as D009 + F033 or F036 -- Exact fee $67.75",
  "F022 (Fractures - Upper Extremity): Monteggia fracture – closed reduction -- Open reduction of ulnar # + closed reduction of radial head dislocation may be claimed as D009 + F033 or F036 -- Exact fee $144.80",
  "F031 (Fractures - Upper Extremity): Radius or ulna fracture – no reduction -- Exact fee $81.30 (MOH Jan 2025) -- Exact fee $81.00",
  "F032 (Fractures - Upper Extremity): Radius or ulna fracture – with reduction -- Exact fee $117.85 (MOH Jan 2025) -- Exact fee $118.00",
  "F034 (Fractures - Upper Extremity): Olecranon fracture – no reduction -- Exact fee $126.25 (MOH Jan 2025) -- Exact fee $126.00",
  "F035 (Fractures - Upper Extremity): Olecranon fracture – with reduction -- Exact fee $129.00 (MOH Jan 2025) -- Exact fee $129.00",
  "F029 (Fractures - Upper Extremity): Epicondyle fracture (no cast) – no reduction -- Exact fee $67.75 (MOH Jan 2025) -- Exact fee $68.00",
  "F037 (Fractures - Upper Extremity): Epicondyle fracture (no cast) – with reduction -- Exact fee $126.25 (MOH Jan 2025) -- Exact fee $126.00",
  "F042 (Fractures - Upper Extremity): Humeral shaft fracture (no cast) – no reduction -- Exact fee $67.80 (MOH Jan 2025) -- Exact fee $68.00",
  "F043 (Fractures - Upper Extremity): Humeral shaft fracture (no cast) – with reduction -- Exact fee $147.60 (MOH Jan 2025) -- Exact fee $148.00",
  "F053 (Fractures - Upper Extremity): Humeral neck fracture (no cast) – no reduction -- Exact fee $67.80 (MOH Jan 2025) -- Exact fee $68.00",
  "F054 (Fractures - Upper Extremity): Humeral neck fracture (no cast) – with reduction -- Exact fee $133.60 (MOH Jan 2025) -- Exact fee $134.00",
  "F134 (Fractures - Lower Extremity): Pelvis fracture with pelvic binder – with reduction -- No fee for no-reduction code; Exact fee $442.45 (MOH Jan 2025) -- Exact fee $442.00",
  "F047 (Fractures - Lower Extremity): Femur tuberosity fracture – no reduction -- Exact fee $67.80 -- Exact fee $68.00",
  "F095 (Fractures - Lower Extremity): Femur fracture – with reduction -- No fee for no-reduction code; Exact fee $407.35 (MOH Jan 2025) -- Exact fee $407.00",
  "F085 (Fractures - Lower Extremity): Patella fracture (no cast) – no reduction -- Exact fee $67.75 (MOH Jan 2025) -- Exact fee $68.00",
  "F078 (Fractures - Lower Extremity): Tibia ± fibula fracture – no reduction -- Exact fee $115.95 (MOH Jan 2025) -- Exact fee $116.00",
  "F079 (Fractures - Lower Extremity): Tibia ± fibula fracture – with reduction -- Exact fee $180.05 (MOH Jan 2025) -- Exact fee $180.00",
  "F082 (Fractures - Lower Extremity): Fibula fracture – no reduction -- Exact fee $67.75 (MOH Jan 2025) -- Exact fee $68.00",
  "F083 (Fractures - Lower Extremity): Fibula fracture – with reduction -- Exact fee $101.25 (MOH Jan 2025) -- Exact fee $101.00",
  "F074 (Fractures - Lower Extremity): Ankle fracture – no reduction -- Exact fee $67.75 (MOH Jan 2025) -- Exact fee $68.00",
  "F075 (Fractures - Lower Extremity): Ankle fracture – with reduction -- Exact fee $144.80 (MOH Jan 2025) -- Exact fee $145.00",
  "F104 (Fractures - Lower Extremity): Ankle fracture with plafond burst – with reduction -- Exact fee $242.25 (MOH Jan 2025) -- Exact fee $242.00",
  "F070 (Fractures - Lower Extremity): Calcaneus fracture – no reduction -- Exact fee $97.35 (MOH Jan 2025) -- Exact fee $97.00",
  "F071 (Fractures - Lower Extremity): Calcaneus fracture – with reduction -- Exact fee $161.45 (MOH Jan 2025) -- Exact fee $161.00",
  "F061 (Fractures - Lower Extremity): Metatarsal fracture (no cast) – no reduction -- Exact fee $49.20 (MOH Jan 2025) -- Exact fee $49.00",
  "F062 (Fractures - Lower Extremity): Metatarsal fracture (with cast) – no reduction -- Exact fee $67.75 (MOH Jan 2025) -- Exact fee $68.00",
  "F063 (Fractures - Lower Extremity): Metatarsal fracture (with cast) – with reduction -- Exact fee $98.35 (MOH Jan 2025) -- Exact fee $98.00",
  "F066 (Fractures - Lower Extremity): Tarsal bone fracture – no reduction -- Exact fee $98.10 (MOH Jan 2025) -- Exact fee $98.00",
  "F067 (Fractures - Lower Extremity): Tarsal bone fracture – with reduction -- Exact fee $165.20 (MOH Jan 2025) -- Exact fee $165.00",
  "F056 (Fractures - Lower Extremity): Phalanx toe fracture – no reduction -- Exact fee $49.20 (MOH Jan 2025); add E560 for each additional toe -- Exact fee $49.00",
  "F058 (Fractures - Lower Extremity): Phalanx toe fracture – with reduction -- Exact fee $72.35 (MOH Jan 2025) -- Exact fee $72.00",
  "E560 (Fractures - Lower Extremity): Phalanx toe – each addl, no reduction -- Exact fee $12.05 (MOH Jan 2025) -- Exact fee $12.00",
  "E561 (Fractures - Lower Extremity): Phalanx toe – each addl, with reduction -- Exact fee $14.90 (MOH Jan 2025) -- Exact fee $15.00",
  "D001 (Dislocation Reductions): Phalanx finger dislocation reduction -- Exact fee $57.50 (MOH Jan 2025) -- Exact fee $58.00",
  "E576 (Dislocation Reductions): Phalanx finger – each addl dislocation -- Exact fee $10.25 (MOH Jan 2025) -- Exact fee $10.00",
  "D003 (Dislocation Reductions): Phalanx finger dislocation reduction – open -- Exact fee $196.50 (MOH Jan 2025) -- Exact fee $197.00",
  "D004 (Dislocation Reductions): Metacarpophalangeal dislocation reduction -- Exact fee $57.50 (MOH Jan 2025) -- Exact fee $58.00",
  "D007 (Dislocation Reductions): Carpal dislocation reduction -- Exact fee $128.05 (MOH Jan 2025) -- Exact fee $128.00",
  "D012 (Dislocation Reductions): Pulled elbow reduction -- Exact fee $39.00 (MOH Jan 2025) -- Exact fee $39.00",
  "D009 (Dislocation Reductions): Elbow dislocation reduction -- Exact fee $84.45 (MOH Jan 2025) -- Exact fee $84.00",
  "D015 (Dislocation Reductions): Shoulder dislocation reduction – no sedation -- Exact fee $49.20 (MOH Jan 2025) -- Exact fee $49.00",
  "D016 (Dislocation Reductions): Shoulder dislocation reduction – with sedation -- Exact fee $111.40 (MOH Jan 2025) -- Exact fee $111.00",
  "D014 (Dislocation Reductions): A/C or S/C joint – no reduction -- Exact fee $67.80 (MOH Jan 2025) -- Exact fee $68.00",
  "D042 (Dislocation Reductions): Hip dislocation reduction -- Exact fee $268.25 (MOH Jan 2025) -- Exact fee $268.00",
  "D038 (Dislocation Reductions): Knee dislocation reduction (no cast) -- Exact fee $207.90 (MOH Jan 2025) -- Exact fee $208.00",
  "D040 (Dislocation Reductions): Patella dislocation – no sedation, no cast -- Exact fee $62.20 (MOH Jan 2025) -- Exact fee $62.00",
  "D031 (Dislocation Reductions): Patella dislocation – with sedation, no cast -- Exact fee $97.35 (MOH Jan 2025) -- Exact fee $97.00",
  "D035 (Dislocation Reductions): Ankle dislocation reduction -- Exact fee $111.35 (MOH Jan 2025) -- Exact fee $111.00",
  "D026 (Dislocation Reductions): Tarso-metatarsal dislocation reduction (no cast) -- Exact fee $147.60 (MOH Jan 2025) -- Exact fee $148.00",
  "D030 (Dislocation Reductions): Metatarsophalangeal dislocation reduction -- Exact fee $57.50 (MOH Jan 2025) -- Exact fee $58.00",
  "D027 (Dislocation Reductions): Interphalangeal toe dislocation reduction -- Exact fee $57.50 (MOH Jan 2025) -- Exact fee $58.00",
  "Z198 (Splints & Casts): Toe cast/splint -- Only if no F or D code billed -- Exact fee $10.25",
  "Z201 (Splints & Casts): Finger splint/cast -- Only if no F or D code billed; Exact fee $10.25 (MOH Jan 2025) -- Exact fee $10.00",
  "Z202 (Splints & Casts): Hand splint/cast -- Only if no F or D code billed; Exact fee $14.90 (MOH Jan 2025) -- Exact fee $15.00",
  "Z199 (Splints & Casts): Foot cast -- Only if no F or D code billed -- Exact fee $14.90",
  "Z203 (Splints & Casts): Arm/forearm/wrist splint/cast -- Only if no F or D code billed; Exact fee $24.10 (MOH Jan 2025) -- Exact fee $24.00",
  "Z213 (Splints & Casts): Below-knee splint/cast -- Only if no F or D code billed; Exact fee $24.10 (MOH Jan 2025) -- Exact fee $24.00",
  "Z211 (Splints & Casts): Long leg splint/cast -- Only if no F or D code billed; Exact fee $28.80 (MOH Jan 2025) -- Exact fee $29.00",
  "Z208 (Splints & Casts): Shoulder spica -- Only if no F or D code billed -- Exact fee $97.35",
  "Z216 (Splints & Casts): Cast wedging / bivalve -- Wedging of casts other than fracture treatment -- Exact fee $10.25",
  "Z204 (Splints & Casts): Cast removal -- Exact fee $10.25 (MOH Jan 2025) -- Exact fee $10.00",
  "G489 (IV Lines & Injections): Venipuncture - adolescent or adult -- Exact fee $3.54",
  "G482 (IV Lines & Injections): Venipuncture - child -- Exact fee $7.35",
  "G480 (IV Lines & Injections): Venipuncture - infant -- Exact fee $9.90",
  "G380 (IV Lines & Injections): IV cutdown including cannulation -- Exact fee $27.05",
  "G282 (IV Lines & Injections): Umbilical vein catheterization (incl. blood sample) -- Exact fee $19.90",
  "G327 (IV Lines & Injections): Femoral catheter insertion (dialysis) -- Exact fee $77.30",
  "Z459 (IV Lines & Injections): Arterial puncture -- Exact fee $10.20",
  "G270 (IV Lines & Injections): Intraosseous infusion -- Exact fee $23.90",
  "G379 (IV Lines & Injections): IV injection - child, adolescent or adult -- Exact fee $6.15",
  "G376 (IV Lines & Injections): IV injection - newborn or infant -- Exact fee $10.20",
  "G372 (IV Lines & Injections): IM / SC / intradermal injection (with visit, each) -- Exact fee $3.89",
  "Z103 (Incision & Drainage): Palmar / plantar space I&D - local anaesthetic -- Exact fee $44.35",
  "Z854 (Incision & Drainage): Eyelid abscess I&D -- Exact fee $60.00",
  "Z728 (Incision & Drainage): Vaginal cyst, abscess or haematoma I&D -- Exact fee $97.20",
  "Z139 (Incision & Drainage): Aspiration of cyst -- Exact fee $37.20",
  "Z172 (Incision & Drainage): Subcutaneous abscess or haematoma - 2 or more (GA) -- Exact fee $66.60",
  "Z108 (Incision & Drainage): Palmar / plantar space I&D - general anaesthetic -- Exact fee $72.00",
  "Z783 (Complex Lacerations): Secondary closure -- Only for delayed surgical closure of a wound; not for routine wound care -- Exact fee $97.35",
  "R790 (Complex Lacerations): Suture of lacerated major artery - traumatic -- Exact fee $316.85",
  "R781 (Complex Lacerations): Ligation of artery - as sole procedure -- Exact fee $170.10",
  "E580 (Complex Lacerations): Extensor tendon repair - each additional (add-on to R578) -- Add-on to R578 -- Exact fee $70.95",
  "R585 (Complex Lacerations): Suture flexor tendon - single -- Exact fee $307.60",
  "E581 (Complex Lacerations): Flexor tendon repair - each additional (add-on to R585) -- Add-on to R585 -- Exact fee $128.95",
  "R629 (Complex Lacerations): Revision of amputated fingertip -- Exact fee $241.55",
  "R601 (Complex Lacerations): Metacarpophalangeal joint capsule repair -- Exact fee $316.75",
  "R150 (Complex Lacerations): [See SOB] R150 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R151 (Complex Lacerations): [See SOB] R151 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R152 (Complex Lacerations): [See SOB] R152 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R153 (Complex Lacerations): [See SOB] R153 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R154 (Complex Lacerations): [See SOB] R154 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "Z117 (Plastic Surgery): Chemical and/or cryotherapy - one or more lesions -- Max 1 per patient per physician per day -- Exact fee $11.65",
  "Z129 (Plastic Surgery): Nail plate excision - multiple -- Exact fee $35.70",
  "Z131 (Plastic Surgery): Radical nail excision + nail bed destruction - multiple -- Exact fee $82.65",
  "Z122 (Plastic Surgery): Cyst, haemangioma or lipoma removal - face/neck (LA) - single lesion -- Exact fee $42.20",
  "Z123 (Plastic Surgery): Cyst, haemangioma or lipoma removal - face/neck (LA) - two lesions -- Exact fee $74.30",
  "Z124 (Plastic Surgery): Cyst, haemangioma or lipoma removal - face/neck (LA) - three or more lesions -- Exact fee $85.45",
  "Z162 (Plastic Surgery): Skin lesion removal by excision and suture - single lesion -- Exact fee $21.90",
  "Z163 (Plastic Surgery): Skin lesion removal by excision and suture - two lesions -- Exact fee $29.05",
  "Z164 (Plastic Surgery): Skin lesion removal by excision and suture - three or more lesions -- Exact fee $48.50",
  "Z081 (Wound Debridement): Wound debridement into subcutaneous tissue - 2 wounds -- Exact fee $30.00",
  "Z082 (Wound Debridement): Wound debridement into subcutaneous tissue - 3 wounds -- Exact fee $45.00",
  "Z083 (Wound Debridement): Wound debridement into subcutaneous tissue - 4+ wounds -- Exact fee $60.00",
  "Z084 (Wound Debridement): Wound debridement into tendon/ligament/bursa/bone - 1-2 wounds -- Exact fee $60.00",
  "Z085 (Wound Debridement): Wound debridement into tendon/ligament/bursa/bone - 3+ wounds -- Exact fee $90.00",
  "R637 (Wound Debridement): Burn debridement - per % BSA (excl. hand, head, neck, eyelid) -- Exact fee $29.65",
  "R660 (Wound Debridement): Burn debridement - hand, each digit -- Exact fee $28.90",
  "R661 (Wound Debridement): Burn debridement - hand, dorsum or palm -- Exact fee $47.95",
  "R662 (Wound Debridement): Burn debridement - face/neck (nose, cheek, lip, ear, forehead, scalp, neck or eyelid) -- Exact fee $28.90",
  "G517 (Critical Care - Other Procedures): Doppler - ankle pressure (incl. ankle-arm index) -- Exact fee $10.05",
  "G115 (Critical Care - Other Procedures): External cardiac pacing - temporary transthoracic -- Not billable with G521, G522, G523, G395 or G391 -- Exact fee $46.30",
  "Z401 (Critical Care - Other Procedures): Pericardiocentesis -- Exact fee $131.70",
  "M137 (Critical Care - Other Procedures): Thoracotomy (with or without biopsy) -- Exact fee $390.65",
  "Z326 (ENT): Tracheostomy tube change -- Exact fee $12.50",
  "F137 (ENT): Nasal fracture - open reduction -- Exact fee $316.35",
  "Z292 (ENT): Direct laryngoscopy - without biopsy -- Exact fee $61.30",
  "S066 (ENT): Post-tonsillectomy haemorrhage - cauterization or suture -- Exact fee $121.05",
  "S023 (ENT): Tooth extraction - single (complete care) -- Exact fee $24.90",
  "E700 (ENT): Tooth extraction - each additional -- Add-on to S023 -- Exact fee $13.40",
  "Z874 (Ophthalmology): Chalazion excision - local anaesthetic, single or multiple -- Exact fee $70.00",
  "E199 (Ophthalmology): Eyelid laceration - full thickness repair -- Ophthalmology should really be doing this. Why are you doing this? -- Exact fee $225.00",
  "E198 (Ophthalmology): Eyelid laceration - full thickness including lid margin -- Add-on / alternative to E199 when lid margin involved -- Exact fee $300.00",
  "E235 (Ophthalmology): Cantholysis - when primary procedure -- Exact fee $107.50",
  "E108 (Ophthalmology): Enucleation, donor eye, post-mortem (one or both) -- Exact fee $131.25",
  "G349 (GI Procedures): Oesophageal tamponade - Blakemore bag insertion -- Exact fee $45.30",
  "G355 (GI Procedures): Nasogastric tube - diagnostic, with or without lavage -- Exact fee $9.60",
  "Z564 (GI Procedures): Diagnostic peritoneal lavage (DPL) - open, without manual exploration -- Exact fee $73.60",
  "Z535 (GI Procedures): Sigmoidoscopy - rigid scope, with or without anoscopy -- Exact fee $36.80",
  "G004 (GI Procedures): Occult blood (hemoccult) -- Exact fee $1.58",
  "Z716 (Obstetrics & Gynaecology): Marsupialization of Bartholin cyst or abscess - GA -- Exact fee $89.80",
  "G365 (Obstetrics & Gynaecology): Cervical cancer screening specimen collection -- Exact fee $12.00",
  "A813 (Obstetrics & Gynaecology): Midwife-Requested Assessment (MAMRA) -- Max one per patient per physician per pregnancy -- Exact fee $111.70",
  "P006 (Obstetrics & Gynaecology): Vaginal delivery -- Exact fee $498.70",
  "E411 (Obstetrics & Gynaecology): Sole delivery premium - add 100% to P006 or P009 -- Add 100% when sole delivery that day; max 25 per physician per fiscal year",
  "P009 (Obstetrics & Gynaecology): Attendance at labour and delivery (non-Ob assist, anaesthetist, or newborn resuscitation) -- Exact fee $498.70",
  "P018 (Obstetrics & Gynaecology): Caesarean section (incl. peri-mortem) -- Exact fee $579.80",
  "S768 (Obstetrics & Gynaecology): Spontaneous abortion, incomplete - including D&C -- Exact fee $113.40",
  "A922 (Obstetrics & Gynaecology): Medical management of ectopic pregnancy - initial service -- Consultations, assessments, and counselling not billable same day -- Exact fee $207.80",
  "G900 (Urology): Residual urine measurement by ultrasound (post-void residual) -- Not billable with pelvic or intracavitary ultrasound -- Exact fee $12.70",
  "G125 (Nerve Blocks): Caudal/lumbar epidural with catheter -- For acute pain management only (>4 hr duration) -- Exact fee $100.00",
  "G218 (Nerve Blocks): Nerve block - ilioinguinal and iliohypogastric nerves -- For acute pain management only (>4 hr duration) -- Exact fee $54.65",
  "G219 (Nerve Blocks): Nerve block - infraorbital nerve -- For acute pain management only (>4 hr duration) -- Exact fee $34.20",
  "G220 (Nerve Blocks): Nerve block - intercostal nerve -- For acute pain management only (>4 hr duration) -- Exact fee $34.20",
  "G221 (Nerve Blocks): Nerve block - each additional intercostal (add-on to G220) -- Add-on to G220 -- Exact fee $16.95",
  "G225 (Nerve Blocks): Nerve block - mental branch of mandibular nerve -- For acute pain management only (>4 hr duration) -- Exact fee $34.20",
  "G250 (Nerve Blocks): Nerve block - maxillary or mandibular division of trigeminal nerve -- For acute pain management only (>4 hr duration) -- Exact fee $75.10",
  "G227 (Nerve Blocks): Nerve block - other cranial nerve -- For acute pain management only (>4 hr duration) -- Exact fee $54.65",
  "G258 (Nerve Blocks): Nerve block - intrapleural, single injection -- For acute pain management only (>4 hr duration) -- Exact fee $44.25",
  "J149P (Routine Procedures): Ultrasound guidance - professional component (aspiration or drainage procedures) -- J138 and J161 rendered same visit are payable at nil -- Exact fee $36.85"
].join('\n');

var SYSTEM_PROMPT =
  'You are an OHIP billing code lookup tool for Emergency Department physicians in Ontario, Canada.\n\n' +
  'The user will type a procedure name, injury, assessment type, or medical abbreviation. ' +
  'Return the 3 to 5 billing codes that best match what they typed -- nothing more.\n\n' +
  'Do NOT suggest assessment codes (H10x, H13x, H15x, H12x), premium codes (H113, H114, E412, E998C), ' +
  'or call-in codes unless the user specifically asks for them. ' +
  'Focus only on the specific procedure, fracture, dislocation, laceration, or service code they are looking for.\n\n' +
  'Common abbreviations: lac=laceration, FB=foreign body, Fx=fracture, I+D=incision and drainage, ' +
  'disloc=dislocation, BPPV=vertigo, CVA=stroke, MI=myocardial infarction\n\n' +
  'Here are all available billing codes:\n' + BILLING_CODES + '\n\n' +
  'Rules:\n' +
  '- Return ONLY codes from the list above, never invent codes\n' +
  '- Return 3 to 5 best matching codes, best match first\n' +
  '- Respond ONLY with valid JSON in this exact format:\n' +
  '  {"results": [{"code":"D015","description":"Shoulder dislocation reduction -- no sedation","category":"Dislocation Reductions","fee":"$49.20"}]}\n' +
  '- fee = extract the dollar amount from "Exact fee $X.XX" in the code description. If no exact fee is listed, use "See SOB"\n' +
  '- No explanation, no markdown, no extra text, just the JSON';

function callOpenAI(apiKey, query) {
  return new Promise(function(resolve, reject) {
    var payload = JSON.stringify({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: query }
      ],
      max_tokens: 600,
      temperature: 0.1,
      response_format: { type: 'json_object' }
    });
    var options = {
      hostname: 'api.openai.com',
      path: '/v1/chat/completions',
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + apiKey,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload)
      }
    };
    var req = https.request(options, function(res) {
      var data = '';
      res.on('data', function(c) { data += c; });
      res.on('end', function() { resolve({ status: res.statusCode, body: data }); });
    });
    req.on('error', reject);
    req.write(payload);
    req.end();
  });
}

exports.handler = function(event) {
  if (event.httpMethod !== 'POST') {
    return Promise.resolve({ statusCode: 405, body: 'Method Not Allowed' });
  }
  var query;
  try { query = JSON.parse(event.body).query; }
  catch(e) { return Promise.resolve({ statusCode: 400, body: JSON.stringify({ error: 'Invalid body' }) }); }
  if (!query || query.trim().length < 2) {
    return Promise.resolve({ statusCode: 400, body: JSON.stringify({ error: 'Query too short' }) });
  }
  var apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return Promise.resolve({ statusCode: 500, body: JSON.stringify({ error: 'API key not configured' }) });
  }
  return callOpenAI(apiKey, query.trim())
    .then(function(r) {
      if (r.status !== 200) {
        console.error('OpenAI error:', r.status, r.body);
        return { statusCode: 502, body: JSON.stringify({ error: 'AI service error' }) };
      }
      var c = JSON.parse(r.body).choices[0].message.content;
      JSON.parse(c);
      return { statusCode: 200, headers: { 'Content-Type': 'application/json' }, body: c };
    })
    .catch(function(err) {
      console.error('Function error:', err);
      return { statusCode: 500, body: JSON.stringify({ error: 'Internal error: ' + err.message }) };
    });
};