const BILLING_CODES = [
  "H101 (ED Assessment): Minor assessment – Day (8am–5pm) -- $23.00",
  "H102 (ED Assessment): Comprehensive assessment – Day (8am–5pm) -- $57.00",
  "H103 (ED Assessment): Multiple assessment – Day (8am–5pm) -- $47.00",
  "H104 (ED Assessment): Reassessment – Day (8am–5pm) -- >2h, change mgmt, not d/c or referral; max 3/pt/day -- $23.00",
  "H131 (ED Assessment): Minor assessment – Eve Mon–Thu (5pm–midnight) -- $30.00",
  "H132 (ED Assessment): Comprehensive assessment – Eve Mon–Thu (5pm–midnight) -- $75.00",
  "H133 (ED Assessment): Multiple assessment – Eve Mon–Thu (5pm–midnight) -- $62.00",
  "H134 (ED Assessment): Reassessment – Eve Mon–Thu (5pm–midnight) -- >2h, change mgmt; max 3/pt/day -- $30.00",
  "H121 (ED Assessment): Minor assessment – Night (midnight–8am) -- $40.00",
  "H122 (ED Assessment): Comprehensive assessment – Night (midnight–8am) -- $100.00",
  "H123 (ED Assessment): Multiple assessment – Night (midnight–8am) -- $81.00",
  "H124 (ED Assessment): Reassessment – Night (midnight–8am) -- >2h, change mgmt; max 3/pt/day -- $40.00",
  "H151 (ED Assessment): Minor assessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight -- $34.00",
  "H152 (ED Assessment): Comprehensive assessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight -- $86.00",
  "H153 (ED Assessment): Multiple assessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight -- $70.00",
  "H154 (ED Assessment): Reassessment – Wkd/Hol (8am–midnight) -- Incl Fri eve 5pm–midnight; max 3/pt/day -- $34.00",
  "H112 (Premiums): Night premium (midnight–8am) -- Per patient visit -- $51.00",
  "H113 (Premiums): Wkd/Hol + Fri eve premium -- Per patient visit; incl Fri eve 5pm–midnight -- $32.00",
  "H114 (Premiums): Weekday eve premium (Mon–Thu) -- Per patient visit; NEW April 2026 -- $24.00",
  "H055 (Consultations): Consultation to ED – FRCPC -- Must record referring MD billing # or contact info -- $126.00",
  "H065 (Consultations): Consultation to ED – CFPC -- Must record referring MD billing # or contact info -- $96.00",
  "K734 (Consultations): Phone consult – referring physician -- ≥10 min; cannot lead to follow-up -- $31.00",
  "K735 (Consultations): Phone consult – consultant physician -- ≥10 min; cannot lead to follow-up -- $40.00",
  "K736 (Consultations): CritiCall telephone consultation – referring physician -- $32.45",
  "H960 (On-Call): On-call travel – Weekday Day -- Max 2/day -- $37.00",
  "H962 (On-Call): On-call travel – Weekday Eve -- Max 2 -- $37.00",
  "H963 (On-Call): On-call travel – Wkd/Hol -- Max 4 -- $37.00",
  "H964 (On-Call): On-call travel – Night -- Unlimited -- $37.00",
  "H980 (On-Call): On-call 1st patient – Weekday Day -- Max 5 -- $20.00",
  "H984 (On-Call): On-call 1st patient – Weekday Eve -- Max 5 -- $60.00",
  "H968 (On-Call): On-call 1st patient – Wkd/Hol -- Max 10 -- $75.00",
  "H986 (On-Call): On-call 1st patient – Night -- Unlimited -- $100.00",
  "H981 (On-Call): On-call addl patient – Weekday Day -- Max 5 -- $20.00",
  "H985 (On-Call): On-call addl patient – Weekday Eve -- Max 5 -- $60.00",
  "H989 (On-Call): On-call addl patient – Wkd/Hol -- Max 10 -- $75.00",
  "H987 (On-Call): On-call addl patient – Night -- Unlimited -- $100.00",
  "K005 (Counselling / Forms): Mental health counselling -- Min 20 min; document mental health dx + times -- $63.00",
  "K061 (Counselling / Forms): Blood sample at request of police officer -- Taking blood in hospital for forensic/legal purposes (e.g. impaired driving) -- $34.80",
  "K028 (Counselling / Forms): Needlestick or STI counselling/treatment -- Per 30 min; document times. Fee updated April 1 2026 -- $80.00",
  "K034 (Counselling / Forms): Telephone report of reportable disease to MOH -- Max 1 per physician per patient per disease per 12 months; must be personally rendered by physician -- $36.00",
  "K015 (Counselling / Forms): Counsel family re: death/catastrophe -- Min 20 min; document times -- $63.00",
  "K623 (Counselling / Forms): Form 1 – psychiatric assessment -- $105.00",
  "K070 (Counselling / Forms): Homecare application -- $32.00",
  "K071 (Counselling / Forms): Acute Home Care Supervision -- max 1 per physician per patient per 2 weeks; first 12 weeks following admission to home care program -- $21.40",
  "K035 (Counselling / Forms): Medical conditions report -- Mandatory report to MOT -- $36.25",
  "A771 (Counselling / Forms): Death certificate -- $34.00",
  "A777 (Counselling / Forms): Pronouncement + death certificate -- $34.00",
  "H105 (Counselling / Forms): Interim admission orders -- $29.00",
  "A320 (Counselling / Forms): MAID consultation -- NEW April 2026 -- $174.25",
  "K101 (Transport): Ground ambulance transfer with patient -- Per 15 min; physician attendance during ground ambulance transfer; fee updated April 1 2026 -- $60.00",
  "K111 (Transport): Air ambulance transfer with patient -- Per 15 min; physician attendance during air ambulance transfer; fee updated April 1 2026 -- $60.00",
  "K112 (Transport): Return trip without patient to place of origin -- Per 30 min; air and ground ambulance; companion to K101/K111 -- $25.00",
  "G521 (Critical Care - Imminent): Imminent life-threatening: 1st 15 min (1st MD) -- Arrest/Trauma; document times; cannot see other pts simultaneously. <strong>E420 +50% trauma premium (ISS > 15)</strong> -- $111.80",
  "G523 (Critical Care - Imminent): Imminent life-threatening: 2nd 15 min (1st MD) -- Arrest/Trauma -- $57.65",
  "G522 (Critical Care - Imminent): Imminent life-threatening: each addl 15 min (max 6) -- Arrest/Trauma; bill for 2nd/3rd MD too -- $38.00",
  "E420 (Critical Care - Imminent): Trauma ISS > 15 premium -- Add to critical care codes",
  "G395 (Critical Care - Potential): Potential life-threatening: 1st 15 min -- Other resuscitation; document times -- $57.45",
  "G391 (Critical Care - Potential): Potential life-threatening: each addl 15 min (max 7) -- Bill for 2nd/3rd MD too -- $30.60",
  "Z437 (Critical Care - Other Procedures): Cardioversion (max 3/day) -- Allowed with G395 but NOT G521 -- $92.00",
  "Z443 (Critical Care - Other Procedures): Insertion of transvenous pacemaker -- $154.10",
  "Z431 (Critical Care - Other Procedures): Repositioning of pacemaker wire -- $64.25",
  "G269 (Critical Care - Other Procedures): Central line -- $31.00",
  "G211 (Critical Care - Other Procedures): Intubation -- Allowed with G395 but NOT G521 -- $38.35",
  "Z325 (Critical Care - Other Procedures): Emergency tracheotomy -- Only billable for life-threatening emergencies where patient is not intubated -- $474.65",
  "E013C (Critical Care - Other Procedures): Anaesthetic management – acute upper airway obstruction (above carina, excl. choanal atresia) -- 10 basic units · Do not bill other C-suffix procedure codes for the same procedure -- $159.60",
  "E639 (Critical Care - Other Procedures): Emergency tracheotomy – anterior cricoid split (add-on) -- Add to Z325 -- $78.50",
  "Z341 (Critical Care - Other Procedures): Chest tube (tube thoracostomy for closed drainage) -- $76.80",
  "Z363 (Critical Care - Other Procedures): Chest tube removal (thoracostomy tube) -- Incl wound closure; fee as of April 1 2026 -- $22.60",
  "Z611 (Critical Care - Other Procedures): Catheter -- $8.55",
  "H100 (Critical Care - Other Procedures): Ultrasound -- $20.00",
  "E009 (Anaesthesia Modifiers): Patient < 1 year old -- Add C4 units; 1 unit = $15.96 (April 2026)",
  "E019 (Anaesthesia Modifiers): Patient 1–8 years old -- Add C2 units",
  "E007 (Anaesthesia Modifiers): Patient 70–79 years old -- Add C1 unit",
  "E018 (Anaesthesia Modifiers): Patient > 80 years old -- Add C3 units",
  "E011 (Anaesthesia Modifiers): Prone position -- Add C4 units",
  "E024 (Anaesthesia Modifiers): Sitting position -- Add C4 units",
  "E022 (Anaesthesia Modifiers): ASA III -- Add C2 units",
  "E017 (Anaesthesia Modifiers): ASA IV -- Add C10 units",
  "E016 (Anaesthesia Modifiers): ASA V -- Add C20 units",
  "E020 (Anaesthesia Modifiers): ASA E (emergency) -- Add C4 units",
  "E010 (Anaesthesia Modifiers): BMI > 40 -- Add C2 units",
  "E400 (Anaesthesia Modifiers): Eve/Wkd/Hol time qualifier -- 3rd line; C = sum of steps 2+3 units",
  "E401 (Anaesthesia Modifiers): Overnight time qualifier -- 3rd line; C = sum of steps 2+3 units",
  "E413 (Anaesthesia Modifiers): Procedure premium – Overnight -- +40% on anaesthesia",
  "E412 (Anaesthesia Modifiers): Procedure premium – Eve/Wkd/Hol -- +20% on anaesthesia",
  "Z154 (Sutures): Face suture 0–5 cm -- Adhesive strips/glue = 50% of fee; on face and/or requires tying of bleeders and/or closure in layers -- $39.00",
  "Z177 (Sutures): Face suture 5.1–10 cm -- 50% of fee if closed with glue or steri-strips; on face and/or requires tying of bleeders and/or closure in layers -- $78.00",
  "Z190 (Sutures): Face suture 10.1–15 cm -- $111.00",
  "Z192 (Sutures): Face suture > 15 cm -- On face and/or requires tying of bleeders and/or closure in layers -- $170.00",
  "Z176 (Sutures): Body suture 0–5 cm -- 50% of fee if closed with glue or steri-strips -- $22.00",
  "Z175 (Sutures): Body suture 5.1–10 cm -- 50% of fee if closed with glue or steri-strips -- $39.00",
  "Z179 (Sutures): Body suture 10.1–15 cm -- 50% of fee if closed with glue or steri-strips -- $55.00",
  "Z191 (Sutures): Body suture > 15 cm -- $85.00",
  "R024 (Complex Lacerations): Acute earlobe repair -- > 20 min; document times -- $101.00",
  "Z189 (Complex Lacerations): Complex laceration zone 1 -- > 20 min; document times -- $92.00",
  "Z187 (Complex Lacerations): Complex face laceration -- > 20 min; document times -- $92.00",
  "R606 (Complex Lacerations): Phalanx amputation repair -- $161.00",
  "Z188 (Complex Lacerations): Complex non-face laceration -- > 20 min; document times -- $92.00",
  "P036 (Complex Lacerations): Vaginal laceration repair -- $54.00",
  "R525 (Complex Lacerations): Muscle & skin repair -- $89.00",
  "R578 (Complex Lacerations): Extensor tendon repair -- $164.00",
  "J149C (Routine Procedures): U/S guided procedure -- $47.00",
  "G269 (Routine Procedures): Central line -- $31.00",
  "G224 (Routine Procedures): Nerve block – local, >4h duration (not a named anatomic block) -- Not billable with lacerations. Use for pudendal, femoral, intercostal, sciatic, ilioinguinal, ulnar, median, radial, or brachial blocks. If a more specific OHIP code exists for the block (e.g. G060, G218, G220), use that instead. -- $16.00",
  "G268 (Routine Procedures): Arterial line -- $31.00",
  "G060 (Routine Procedures): Major nerve block (provides analgesia > 4h) -- $55.00",
  "G061 (Routine Procedures): Minor nerve block (provides analgesia > 4h) -- $30.00",
  "G260 (Routine Procedures): Major plexus block – 3-in-1 (provides analgesia > 4h) -- $80.00",
  "G231 (Routine Procedures): Dental block -- $34.00",
  "G370 (Routine Procedures): Knee aspiration -- $20.00",
  "G328 (Routine Procedures): Joint aspiration (not knee) -- $40.00",
  "E446 (Routine Procedures): U/S guided aspiration (addl) -- Add-on code -- $30.00",
  "Z080 (Routine Procedures): Wound/ulcer debridement -- $20.00",
  "Z331 (Routine Procedures): Diagnostic thoracentesis -- $32.00",
  "Z332 (Routine Procedures): Therapeutic thoracentesis -- $59.00",
  "Z590 (Routine Procedures): Diagnostic paracentesis -- $31.00",
  "Z591 (Routine Procedures): Therapeutic paracentesis -- $58.00",
  "Z763 (Routine Procedures): Paracentesis with lavage for diagnosis -- $38.70",
  "G356 (Routine Procedures): NG tube insertion -- $34.00",
  "Z520 (Routine Procedures): G tube change -- $11.00",
  "Z538 (Routine Procedures): Hernia reduction -- $25.00",
  "Z543 (Routine Procedures): Anoscopy / Proctoscopy -- $9.00",
  "Z110 (Routine Procedures): Subungual hematoma drainage -- $17.00",
  "Z608 (Routine Procedures): Manual Foley declogging -- $59.00",
  "Z128 (Routine Procedures): Nail removal -- $33.00",
  "A920 (Routine Procedures): Misoprostol (including assessment) -- $161.00",
  "Z130 (Routine Procedures): Nail removal + cautery -- $63.00",
  "S756 (Routine Procedures): Removal of POC from OS -- $112.00",
  "G313 (Routine Procedures): EKG -- Must be discharged patient -- $4.00",
  "Z804 (Routine Procedures): Lumbar puncture -- $150.00",
  "Z399 (Routine Procedures): Endoscopy -- $93.00",
  "L810 (Routine Procedures): Description of CSF -- $25.00",
  "G435 (Routine Procedures): Tonometry -- $5.10",
  "Z432 (Routine Procedures): Exam under anaesthesia -- $54.00",
  "G552 (Routine Procedures): IUD removal (without sedation) -- Removal of intrauterine contraceptive device without sedation -- $20.00",
  "Z735 (Routine Procedures): IUD removal / exam ± insertion under GA -- Exam and/or dilatation incl insertion and/or removal of IUD under general anaesthetic as sole procedure -- $56.70",
  "Z756 (Routine Procedures): Rectal disimpaction / fecal disimpaction -- Was $36.80 → $46.00 April 2026 -- $46.00",
  "H264 (Routine Procedures): ED pelvic exam with speculum -- NEW April 2026 -- $12.00",
  "Z101 (Incision & Drainage): Abscess I&D – one abscess (LA) -- $28.00",
  "Z226 (Incision & Drainage): Elbow bursa I&D -- $97.00",
  "Z102 (Incision & Drainage): Abscess I&D – one abscess (GA) -- $49.00",
  "Z506 (Incision & Drainage): Oral abscess I&D -- $51.00",
  "Z173 (Incision & Drainage): Abscess I&D – two abscesses (LA) -- $33.00",
  "Z714 (Incision & Drainage): Vulva, Bartholin or Skene's gland abscess I&D – local anaesthetic -- $25.40",
  "Z174 (Incision & Drainage): Abscess I&D – 3+ abscesses (LA) -- $45.00",
  "Z715 (Incision & Drainage): Vulva, Bartholin or Skene's gland abscess I&D – general anaesthetic -- $102.05",
  "Z104 (Incision & Drainage): Perianal abscess I&D (LA) -- Was $20.10 → $33.25 (+65%) April 2026 -- $33.00",
  "Z140 (Incision & Drainage): Breast abscess I&D (LA) -- $33.00",
  "Z105 (Incision & Drainage): Perianal abscess I&D (GA) -- $72.00",
  "Z740 (Incision & Drainage): Breast abscess I&D (GA) -- $75.00",
  "Z106 (Incision & Drainage): Pilonidal abscess I&D (LA) -- $49.00",
  "Z227 (Incision & Drainage): IM abscess/hematoma I&D -- $101.00",
  "Z107 (Incision & Drainage): Pilonidal abscess I&D (GA) -- $118.00",
  "Z510 (Incision & Drainage): Peritonsillar abscess (PTA) drainage -- $91.00",
  "Z545 (Incision & Drainage): Hemorrhoid I&D -- $25.00",
  "E318 (Incision & Drainage): Pinna hematoma drainage -- $92.00",
  "Z114 (Foreign Bodies): Foreign body removal – skin (LA) -- $25.00",
  "Z915 (Foreign Bodies): Foreign body removal – ear (LA) -- $11.00",
  "Z115 (Foreign Bodies): Foreign body removal – skin (GA) -- $89.00",
  "Z866 (Foreign Bodies): Foreign body removal – ear (GA) -- $51.00",
  "R517 (Foreign Bodies): Foreign body removal – muscle -- $108.00",
  "Z311 (Foreign Bodies): Foreign body removal – nose (LA) -- $11.00",
  "Z541 (Foreign Bodies): Foreign body removal – rectum (GA) -- $58.00",
  "Z312 (Foreign Bodies): Foreign body removal – nose (GA) -- $51.00",
  "Z847 (Foreign Bodies): Foreign body removal – eye (1 FB) -- Also used for chalazion excision -- $33.00",
  "Z848 (Foreign Bodies): Foreign body removal – eye (2 FBs) -- $45.00",
  "Z852 (Foreign Bodies): Foreign body removal – eye, embedded (GA) -- $74.20",
  "Z432A (Foreign Bodies): Foreign body removal – vagina (GA) -- $54.00",
  "S547 (Foreign Bodies): Foreign body removal – urethra -- $171.00",
  "E023C (Foreign Bodies): Foreign body removal – vagina with sedation -- 6 anaesthesia units",
  "G420 (ENT): Ear syringe/irrigation -- Insured only if: (a) impacted wax causing hearing loss unresponsive to topical cerumenolytics; or (b) immediate removal needed to visualize TM or ear canal for diagnostic/therapeutic purposes -- $11.00",
  "G403 (ENT): Epley manoeuvre -- $21.00",
  "Z315 (ENT): Anterior nasal pack -- $15.00",
  "Z321 (ENT): Direct laryngoscopy -- $61.00",
  "Z316 (ENT): Posterior nasal pack -- Unilateral or bilateral -- $36.00",
  "Z322 (ENT): Direct laryngoscopy with FB removal -- $106.00",
  "Z314 (ENT): Nasal cautery -- $12.00",
  "Z301 (ENT): Nasal abscess or haematoma I&D -- $55.60",
  "Z324 (ENT): Indirect laryngoscopy with FB removal -- $45.00",
  "F136 (ENT): Nasal fracture reduction -- $102.00",
  "D062 (ENT): TMJ reduction -- $52.00",
  "F004 (Fractures - Upper Extremity): Phalanx finger fracture – closed, no reduction -- add E558 for each additional finger -- $49.20",
  "F005 (Fractures - Upper Extremity): Phalanx finger fracture – closed, with reduction -- Ortho f/u = 75%; add E558 for each additional finger -- $99.25",
  "E558 (Fractures - Upper Extremity): Phalanx finger – each addl fracture with reduction -- $22.25",
  "F007 (Fractures - Upper Extremity): Phalanx finger fracture – open, with reduction -- $298.45",
  "F008 (Fractures - Upper Extremity): Metacarpal fracture – no reduction -- $49.20",
  "F009 (Fractures - Upper Extremity): Metacarpal fracture – with reduction -- $99.25",
  "F012 (Fractures - Upper Extremity): Bennett's fracture – no reduction -- $49.20",
  "F013 (Fractures - Upper Extremity): Bennett's fracture – with reduction -- $119.80",
  "F018 (Fractures - Upper Extremity): Scaphoid fracture – no reduction -- $49.20",
  "F102 (Fractures - Upper Extremity): Other carpal fracture – no reduction -- $49.20",
  "F016 (Fractures - Upper Extremity): Other carpal fracture – with reduction -- $115.10",
  "F027 (Fractures - Upper Extremity): Colles/Smith fracture – no reduction -- $67.75",
  "F028 (Fractures - Upper Extremity): Colles/Smith fracture – with reduction -- $109.45",
  "F046 (Fractures - Upper Extremity): Colles/Smith fracture – with reduction + sedation -- $149.35",
  "F024 (Fractures - Upper Extremity): Radius and ulna shaft fracture – no reduction, rigid immobilization -- $67.75",
  "F014 (Fractures - Upper Extremity): Monteggia fracture – no reduction, rigid immobilization -- Open reduction of ulnar # + closed reduction of radial head dislocation may be claimed as D009 + F033 or F036 -- $67.75",
  "F022 (Fractures - Upper Extremity): Monteggia fracture – closed reduction -- Open reduction of ulnar # + closed reduction of radial head dislocation may be claimed as D009 + F033 or F036 -- $144.80",
  "F031 (Fractures - Upper Extremity): Radius or ulna fracture – no reduction -- $81.30",
  "F032 (Fractures - Upper Extremity): Radius or ulna fracture – with reduction -- $117.85",
  "F039 (Fractures - Upper Extremity): Transcondylar / condylar fracture – no reduction -- $67.75",
  "F040 (Fractures - Upper Extremity): Transcondylar / condylar fracture – closed reduction -- $298.35",
  "F034 (Fractures - Upper Extremity): Olecranon fracture – no reduction -- $126.25",
  "F035 (Fractures - Upper Extremity): Olecranon fracture – with reduction -- $129.00",
  "F029 (Fractures - Upper Extremity): Epicondyle fracture (no cast) – no reduction -- $67.75",
  "F037 (Fractures - Upper Extremity): Epicondyle fracture (no cast) – with reduction -- $126.25",
  "F042 (Fractures - Upper Extremity): Humeral shaft fracture (no cast) – no reduction -- $67.80",
  "F043 (Fractures - Upper Extremity): Humeral shaft fracture (no cast) – with reduction -- $147.60",
  "F053 (Fractures - Upper Extremity): Humeral neck fracture (no cast) – no reduction -- $67.80",
  "F054 (Fractures - Upper Extremity): Humeral neck fracture (no cast) – with reduction -- $133.60",
  "F110 (Fractures - Upper Extremity): Clavicle fracture – closed reduction with anaesthetic -- Visit fee only if no reduction performed -- $62.20",
  "F134 (Fractures - Lower Extremity): Pelvis fracture with pelvic binder – with reduction -- No fee for no-reduction code -- $442.45",
  "F047 (Fractures - Lower Extremity): Femur tuberosity fracture – no reduction -- $67.80",
  "F094 (Fractures - Lower Extremity): Femur fracture – closed reduction with skin traction or Pavlik harness (infant) -- $258.00",
  "F095 (Fractures - Lower Extremity): Femur fracture – closed reduction with external fixation, skeletal traction, or hip spica cast (infant or child) -- $407.35",
  "F093 (Fractures - Lower Extremity): Diaphyseal or metaphyseal distal femur fracture – with or without intramedullary fixation -- $407.35",
  "F085 (Fractures - Lower Extremity): Patella fracture (no cast) – no reduction -- $67.75",
  "F078 (Fractures - Lower Extremity): Tibia ± fibula fracture – no reduction -- $115.95",
  "F079 (Fractures - Lower Extremity): Tibia ± fibula fracture – with reduction -- $180.05",
  "F082 (Fractures - Lower Extremity): Fibula fracture – no reduction -- $67.75",
  "F083 (Fractures - Lower Extremity): Fibula fracture – with reduction -- $101.25",
  "F074 (Fractures - Lower Extremity): Ankle fracture – no reduction -- $67.75",
  "F075 (Fractures - Lower Extremity): Ankle fracture – with reduction -- $144.80",
  "F104 (Fractures - Lower Extremity): Ankle fracture with plafond burst – with reduction -- $242.25",
  "F070 (Fractures - Lower Extremity): Calcaneus fracture – no reduction -- $97.35",
  "F071 (Fractures - Lower Extremity): Calcaneus fracture – with reduction -- $161.45",
  "F061 (Fractures - Lower Extremity): Metatarsal fracture (no cast) – no reduction -- $49.20",
  "F062 (Fractures - Lower Extremity): Metatarsal fracture (with cast) – no reduction -- $67.75",
  "F063 (Fractures - Lower Extremity): Metatarsal fracture (with cast) – with reduction -- $98.35",
  "F066 (Fractures - Lower Extremity): Tarsal bone fracture – no reduction -- $98.10",
  "F067 (Fractures - Lower Extremity): Tarsal bone fracture – with reduction -- $165.20",
  "F056 (Fractures - Lower Extremity): Phalanx toe fracture – no reduction -- add E560 for each additional toe -- $49.20",
  "F058 (Fractures - Lower Extremity): Phalanx toe fracture – with reduction -- $72.35",
  "E560 (Fractures - Lower Extremity): Phalanx toe – each addl, no reduction -- $12.05",
  "E561 (Fractures - Lower Extremity): Phalanx toe – each addl, with reduction -- $14.90",
  "D001 (Dislocation Reductions): Phalanx finger dislocation reduction -- $57.50",
  "E576 (Dislocation Reductions): Phalanx finger – each addl dislocation -- $10.25",
  "D003 (Dislocation Reductions): Phalanx finger dislocation reduction – open -- $196.50",
  "D004 (Dislocation Reductions): Metacarpophalangeal dislocation reduction -- $57.50",
  "D007 (Dislocation Reductions): Carpal dislocation reduction -- $128.05",
  "D012 (Dislocation Reductions): Pulled elbow reduction -- $39.00",
  "D009 (Dislocation Reductions): Elbow dislocation reduction -- $84.45",
  "D015 (Dislocation Reductions): Shoulder dislocation reduction – no sedation -- $49.20",
  "D016 (Dislocation Reductions): Shoulder dislocation reduction – with sedation -- $111.40",
  "D014 (Dislocation Reductions): A/C or S/C joint – no reduction -- $67.80",
  "D025 (Dislocation Reductions): A/C or S/C joint – closed reduction with anaesthetic -- $134.55",
  "D042 (Dislocation Reductions): Hip dislocation reduction -- $268.25",
  "D038 (Dislocation Reductions): Knee dislocation reduction (no cast) -- $207.90",
  "D040 (Dislocation Reductions): Patella dislocation – no sedation, no cast -- $62.20",
  "D031 (Dislocation Reductions): Patella dislocation – with sedation, no cast -- $97.35",
  "D035 (Dislocation Reductions): Ankle dislocation reduction -- $111.35",
  "D026 (Dislocation Reductions): Tarso-metatarsal dislocation reduction (no cast) -- $147.60",
  "D030 (Dislocation Reductions): MTP (Metatarsophalangeal) dislocation reduction -- $57.50",
  "D027 (Dislocation Reductions): Interphalangeal toe dislocation reduction -- $57.50",
  "Z198 (Splints & Casts): Toe cast/splint -- Only if no F or D code billed -- $10.25",
  "Z201 (Splints & Casts): Finger splint/cast -- Only if no F or D code billed -- $10.25",
  "Z202 (Splints & Casts): Hand splint/cast -- Only if no F or D code billed -- $14.90",
  "Z199 (Splints & Casts): Foot cast -- Only if no F or D code billed -- $14.90",
  "Z203 (Splints & Casts): Arm/forearm/wrist splint/cast -- Only if no F or D code billed -- $24.10",
  "Z213 (Splints & Casts): Below-knee splint/cast -- Only if no F or D code billed -- $24.10",
  "Z211 (Splints & Casts): Long leg splint/cast -- Only if no F or D code billed -- $28.80",
  "Z208 (Splints & Casts): Shoulder spica -- Only if no F or D code billed -- $97.35",
  "Z216 (Splints & Casts): Cast wedging / bivalve -- Wedging of casts other than fracture treatment -- $10.25",
  "Z204 (Splints & Casts): Cast removal -- $10.25",
  "G489 (IV Lines & Injections): Venipuncture - adolescent or adult -- $3.54",
  "G482 (IV Lines & Injections): Venipuncture - child -- $7.35",
  "G480 (IV Lines & Injections): Venipuncture - infant -- $9.90",
  "G380 (IV Lines & Injections): IV cutdown including cannulation -- $27.05",
  "G282 (IV Lines & Injections): Umbilical vein catheterization (incl. blood sample) -- $19.90",
  "G327 (IV Lines & Injections): Femoral catheter insertion (dialysis) -- $77.30",
  "Z459 (IV Lines & Injections): Arterial puncture -- $10.20",
  "G270 (IV Lines & Injections): Intraosseous infusion -- $23.90",
  "G379 (IV Lines & Injections): IV injection - child, adolescent or adult -- $6.15",
  "G376 (IV Lines & Injections): IV injection - newborn or infant -- $10.20",
  "G372 (IV Lines & Injections): IM / SC / intradermal injection (with visit, each) -- $3.89",
  "Z103 (Incision & Drainage): Palmar / plantar space I&D - local anaesthetic -- $44.35",
  "Z854 (Incision & Drainage): Eyelid abscess I&D -- $60.00",
  "Z728 (Incision & Drainage): Vaginal cyst, abscess or haematoma I&D -- $97.20",
  "Z139 (Incision & Drainage): Aspiration of cyst -- $37.20",
  "Z172 (Incision & Drainage): Subcutaneous abscess or haematoma - 2 or more (GA) -- $66.60",
  "Z108 (Incision & Drainage): Palmar / plantar space I&D - general anaesthetic -- $72.00",
  "Z783 (Complex Lacerations): Secondary closure -- Only for delayed surgical closure of a wound; not for routine wound care -- $97.35",
  "R790 (Complex Lacerations): Suture of lacerated major artery - traumatic -- $316.85",
  "R781 (Complex Lacerations): Ligation of artery - as sole procedure -- $170.10",
  "E580 (Complex Lacerations): Extensor tendon repair - each additional (add-on to R578) -- Add-on to R578 -- $70.95",
  "R585 (Complex Lacerations): Suture flexor tendon - single -- $307.60",
  "E581 (Complex Lacerations): Flexor tendon repair - each additional (add-on to R585) -- Add-on to R585 -- $128.95",
  "R629 (Complex Lacerations): Revision of amputated fingertip -- $241.55",
  "R601 (Complex Lacerations): Metacarpophalangeal joint capsule repair -- $316.75",
  "R150 (Complex Lacerations): [See SOB] R150 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R151 (Complex Lacerations): [See SOB] R151 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R152 (Complex Lacerations): [See SOB] R152 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R153 (Complex Lacerations): [See SOB] R153 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "R154 (Complex Lacerations): [See SOB] R154 - placeholder description -- NOT eligible for payment to General/Family Practice (00) or Emergency Medicine physicians",
  "Z117 (Plastic Surgery): Chemical and/or cryotherapy - one or more lesions -- Max 1 per patient per physician per day -- $11.65",
  "Z129 (Plastic Surgery): Nail plate excision - multiple -- $35.70",
  "Z131 (Plastic Surgery): Radical nail excision + nail bed destruction - multiple -- $82.65",
  "Z122 (Plastic Surgery): Cyst, haemangioma or lipoma removal - face/neck (LA) - single lesion -- $42.20",
  "Z123 (Plastic Surgery): Cyst, haemangioma or lipoma removal - face/neck (LA) - two lesions -- $74.30",
  "Z124 (Plastic Surgery): Cyst, haemangioma or lipoma removal - face/neck (LA) - three or more lesions -- $85.45",
  "Z162 (Plastic Surgery): Skin lesion removal by excision and suture - single lesion -- $21.90",
  "Z163 (Plastic Surgery): Skin lesion removal by excision and suture - two lesions -- $29.05",
  "Z164 (Plastic Surgery): Skin lesion removal by excision and suture - three or more lesions -- $48.50",
  "Z081 (Wound Debridement): Wound debridement into subcutaneous tissue - 2 wounds -- $30.00",
  "Z082 (Wound Debridement): Wound debridement into subcutaneous tissue - 3 wounds -- $45.00",
  "Z083 (Wound Debridement): Wound debridement into subcutaneous tissue - 4+ wounds -- $60.00",
  "Z084 (Wound Debridement): Wound debridement into tendon/ligament/bursa/bone - 1-2 wounds -- $60.00",
  "Z085 (Wound Debridement): Wound debridement into tendon/ligament/bursa/bone - 3+ wounds -- $90.00",
  "R637 (Wound Debridement): Burn debridement - per % BSA (excl. hand, head, neck, eyelid) -- $29.65",
  "R660 (Wound Debridement): Burn debridement - hand, each digit -- $28.90",
  "R661 (Wound Debridement): Burn debridement - hand, dorsum or palm -- $47.95",
  "R662 (Wound Debridement): Burn debridement - face/neck (nose, cheek, lip, ear, forehead, scalp, neck or eyelid) -- $28.90",
  "G517 (Critical Care - Other Procedures): Doppler - ankle pressure (incl. ankle-arm index) -- $10.05",
  "G115 (Critical Care - Other Procedures): External cardiac pacing - temporary transthoracic -- Not billable with G521, G522, G523, G395 or G391 -- $46.30",
  "Z401 (Critical Care - Other Procedures): Pericardiocentesis -- $131.70",
  "M137 (Critical Care - Other Procedures): Thoracotomy (with or without biopsy) -- $390.65",
  "Z326 (ENT): Tracheostomy tube change -- $12.50",
  "F137 (ENT): Nasal fracture - open reduction -- $316.35",
  "Z292 (ENT): Direct laryngoscopy - without biopsy -- $61.30",
  "S066 (ENT): Post-tonsillectomy haemorrhage - cauterization or suture -- $121.05",
  "S023 (ENT): Tooth extraction - single (complete care) -- $24.90",
  "E700 (ENT): Tooth extraction - each additional -- Add-on to S023 -- $13.40",
  "Z874 (Ophthalmology): Chalazion excision - local anaesthetic, single or multiple -- $70.00",
  "E199 (Ophthalmology): Eyelid laceration - full thickness repair -- Ophthalmology should really be doing this. Why are you doing this? -- $225.00",
  "E198 (Ophthalmology): Eyelid laceration - full thickness including lid margin -- Add-on / alternative to E199 when lid margin involved -- $300.00",
  "E235 (Ophthalmology): Cantholysis - when primary procedure -- $107.50",
  "E108 (Ophthalmology): Enucleation, donor eye, post-mortem (one or both) -- $131.25",
  "G349 (GI Procedures): Oesophageal tamponade - Blakemore bag insertion -- $45.30",
  "G355 (GI Procedures): Nasogastric tube - diagnostic, with or without lavage -- $9.60",
  "Z564 (GI Procedures): Diagnostic peritoneal lavage (DPL) - open, without manual exploration -- $73.60",
  "Z535 (GI Procedures): Sigmoidoscopy - rigid scope, with or without anoscopy -- $36.80",
  "G004 (GI Procedures): Occult blood (hemoccult) -- $1.58",
  "Z716 (Obstetrics & Gynaecology): Marsupialization of Bartholin cyst or abscess - GA -- $89.80",
  "G365 (Obstetrics & Gynaecology): Cervical cancer screening specimen collection -- $12.00",
  "A813 (Obstetrics & Gynaecology): Midwife-Requested Assessment (MAMRA) -- Max one per patient per physician per pregnancy -- $111.70",
  "P006 (Obstetrics & Gynaecology): Vaginal delivery -- $498.70",
  "E411 (Obstetrics & Gynaecology): Sole delivery premium - add 100% to P006 or P009 -- Add 100% when sole delivery that day; max 25 per physician per fiscal year",
  "P009 (Obstetrics & Gynaecology): Attendance at labour and delivery (non-Ob assist, anaesthetist, or newborn resuscitation) -- $498.70",
  "P018 (Obstetrics & Gynaecology): Caesarean section (incl. peri-mortem) -- $579.80",
  "S768 (Obstetrics & Gynaecology): Spontaneous abortion, incomplete - including D&C -- $113.40",
  "A922 (Obstetrics & Gynaecology): Medical management of ectopic pregnancy - initial service -- Consultations, assessments, and counselling not billable same day -- $207.80",
  "G900 (Urology): Residual urine measurement by ultrasound (post-void residual) -- Not billable with pelvic or intracavitary ultrasound -- $12.70",
  "G125 (Nerve Blocks): Caudal/lumbar epidural with catheter -- For acute pain management only (>4 hr duration) -- $100.00",
  "G218 (Nerve Blocks): Nerve block - ilioinguinal and iliohypogastric nerves -- For acute pain management only (>4 hr duration) -- $54.65",
  "G219 (Nerve Blocks): Nerve block - infraorbital nerve -- For acute pain management only (>4 hr duration) -- $34.20",
  "G220 (Nerve Blocks): Nerve block - intercostal nerve -- For acute pain management only (>4 hr duration) -- $34.20",
  "G221 (Nerve Blocks): Nerve block - each additional intercostal (add-on to G220) -- Add-on to G220 -- $16.95",
  "G225 (Nerve Blocks): Nerve block - mental branch of mandibular nerve -- For acute pain management only (>4 hr duration) -- $34.20",
  "G250 (Nerve Blocks): Nerve block - maxillary or mandibular division of trigeminal nerve -- For acute pain management only (>4 hr duration) -- $75.10",
  "G227 (Nerve Blocks): Nerve block - other cranial nerve -- For acute pain management only (>4 hr duration) -- $54.65",
  "G258 (Nerve Blocks): Nerve block - intrapleural, single injection -- For acute pain management only (>4 hr duration) -- $44.25",
  "J149P (Routine Procedures): Ultrasound guidance - professional component (aspiration or drainage procedures) -- J138 and J161 rendered same visit are payable at nil -- $36.85",
].join('\n');

const SYSTEM_PROMPT =
  'You are an OHIP billing code lookup tool for Emergency Department physicians in Ontario, Canada.\n\n' +
  'The user will type a procedure name, injury, assessment type, or medical abbreviation. ' +
  'Return the 3 to 5 billing codes that best match what they typed -- nothing more.\n\n' +
  'Do NOT suggest assessment codes (H10x, H13x, H15x, H12x), premium codes (H113, H114, E412, E998C), ' +
  'or call-in codes unless the user specifically asks for them. ' +
  'Focus only on the specific procedure, fracture, dislocation, laceration, or service code they are looking for.\n\n' +
  'Common abbreviations: lac=laceration, FB=foreign body, Fx=fracture, I+D=incision and drainage, ' +
  'disloc=dislocation, BPPV=vertigo, CVA=stroke, MI=myocardial infarction\n\n' +
  'Here are all available billing codes:\n' + BILLING_CODES + '\n\n' +
  'Rules:\n' +
  '- Return ONLY codes from the list above, never invent codes\n' +
  '- Return 3 to 5 best matching codes, best match first\n' +
  '- Respond with ONLY 3 to 5 JSON objects, one per line -- no surrounding array, brackets, markdown, or explanation\n' +
  '- Each line format: {"code":"D015","description":"Shoulder dislocation reduction -- no sedation","category":"Dislocation Reductions","fee":"$49.20"}\n' +
  '- fee = the dollar amount at the end of the code entry (after the final "--"). If none is present, use "See SOB"';

export default async (req) => {
  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }

  let query;
  try {
    ({ query } = await req.json());
  } catch (e) {
    return new Response(JSON.stringify({ error: 'Invalid body' }), { status: 400 });
  }
  if (!query || query.trim().length < 2) {
    return new Response(JSON.stringify({ error: 'Query too short' }), { status: 400 });
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return new Response(JSON.stringify({ error: 'API key not configured' }), { status: 500 });
  }

  let upstream;
  try {
    upstream = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: query.trim() },
        ],
        max_tokens: 600,
        temperature: 0.1,
        stream: true,
      }),
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: 'Internal error: ' + err.message }), { status: 500 });
  }

  if (!upstream.ok || !upstream.body) {
    const errText = await upstream.text().catch(() => '');
    console.error('OpenAI error:', upstream.status, errText);
    return new Response(JSON.stringify({ error: 'AI service error' }), { status: 502 });
  }

  // Proxy OpenAI's SSE stream straight through so the client can render
  // results as they arrive instead of waiting for the full completion.
  return new Response(upstream.body, {
    status: 200,
    headers: { 'Content-Type': 'text/event-stream; charset=utf-8' },
  });
};
